secrets:
  BUILDKITE_API_TOKEN: UA_TOKEN
steps:
  - label: "Generate some logs to summarize"
    key: "log_thing"
    command: |
      echo "ðŸ—ï¸ Build Health Report"
      echo "====================="
      echo ""
      echo "Coffee consumed: $((RANDOM % 10 + 1)) cups"
      echo "Tests passed: $((RANDOM % 100 + 50))%"
      echo "Code quality: $(shuf -n 1 -e "Excellent" "Good" "Could be better" "Needs improvement")"
      echo "Developer mood: $(shuf -n 1 -e "ðŸ˜Š" "ðŸ¤”" "ðŸ˜´" "ðŸŽ‰" "ðŸ”¥")"
      echo "Bugs fixed: $((RANDOM % 20))"
      echo "New bugs introduced: $((RANDOM % 5))"
      echo ""
      echo "Notable events during build:"
      echo "- Agent successfully avoided distraction by cute dog videos"
      echo "- Cache hit rate better than expected"
      echo "- No rubber ducks were harmed in the making of this build"
      echo "=== Error detected ==="
      echo "Something went wrong!"
      exit 1
  - label: "Create a random file and put some nonsense in it"
    key: "file_thing"
    command: |
      cat > myfile.txt << 'EOF'
      This is some content
      Multiple lines work too
      SNAAAKES!âœ¨
      EOF
      cat myfile.txt
  - label: ":robot: summarize"
    command: "echo 'Running some build step...'"
    depends_on:
      - step: "log_thing"
        allow_failure: true
      - step: "file_thing"
        allow_failure: true
    plugins:
      - jfhinchcliffe/claude-summarize#059cda42c3ccb526380bf12bdeada5bd7cfcf85e:
          trigger: "always"
          annotate: true
          hosted_models: true
          custom_prompt: "Check the logs from this build and summarize"
          analysis_level: "build"
